<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateFoundersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('founders', function (Blueprint $table) {
            //Generated by Artisan
            $table->increments('id');
            $table->timestamps();

            //Developer Created
            $table->integer('user_id')->unsigned();
            $table->foreign('user_id')
                ->references('id')
                ->on('users');
            $table->string('fname');
            $table->string('lname');
            $table->string('company_name');
            $table->string('company_street');
            $table->string('company_city');
            $table->string('company_state');
            $table->string('company_zip');
            $table->string('company_phone');
            $table->string('company_industry');
            $table->integer('company_mktcap');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::drop('founders');
    }
}
